name: Condições

on:
  push:
    branches: [main]

jobs:
  condicoes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Capturar hora
        id: time
        run: echo "hour=$(date +%H)" >> $GITHUB_OUTPUT

      - name: Rodar apenas de noite
        if: contains('18,19,20,21,22,23,00,01,02,03,04,05,06', steps.time.outputs.hour)
        run: echo "Executando porque é noite!"

      - name: Rodar apenas aos sábados
        run: |
          dia=$(date +%u)
          if [ "$dia" -eq 6 ]; then
            echo "Hoje é sábado!"
          else
            echo "Não é sábado!"
          fi

      - name: Verificar arquivos >100KB
        run: |
          echo "Arquivos maiores que 100KB:"
          find . -type f -size +100k -exec ls -lh {} \; || echo "Nenhum arquivo grande encontrado."
