name: Hello World

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello World!"

      - name: Criar/atualizar txt
        run: |
          echo "Hello word" > helloWord.txt
